on:
  push:
    tags:
      - 'v*'
      
name: Release
jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@2
      - name: Create Release for Tag
        id: release_tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release  ${{ github.ref }}
          body: |
              Please refer to [CHANGELOG.md](https://github.com/pigsking/vue-mark-calendar/blob/master/CHANGELOG.md) for details.